@url = http://localhost:5069

###
GET {{url}}

###
@email = user1@chime.io
@adminEmail = admin1@chime.io
@password = Secret123!

### Register as the regular user
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": ""
}