@url = http://localhost:5069/customers
@customerId = 18665517-3475-40ce-86a4-220649b8e3f5

###
GET {{url}}

###
GET {{url}}/{{customerId}}

###
POST {{url}}
Content-Type: application/json

{
  "email": "user1@chime.io"
}

###
PUT {{url}}/complete
Content-Type: application/json

{
  "name": "user1",
  "fullName": "John Doe",
  "address": "Test street 123",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "ABC1234567"
}

###
PUT {{url}}/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/unlock
Content-Type: application/json

{
}